# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homelyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentoutProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=30, unique=True)),
                ('house_address', models.CharField(max_length=50, unique=True)),
                ('house_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
