# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelyapp', '0002_rentoutproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentoutproperties',
            name='house_rented',
            field=models.BooleanField(default=False),
        ),
    ]
